# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: juansandoval

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-mysql2_production
  pool: 5
  username: root
  password: password1
  socket: /tmp/mysql.sock
